export type IslamicItem = {
  slug: string
  category: string
  title: string
  date: string
  excerpt: string
  content: string[]
}

export const islamicItems: IslamicItem[] = [
  { slug: 'menjaga-ukhuwah-dan-adab-bermasyarakat', category: 'Khutbah', title: 'Menjaga Ukhuwah dan Adab Bermasyarakat', date: '27 Agustus 2026', excerpt: 'Ukhuwah tumbuh dari kebiasaan menjaga adab, menyapa, dan saling membantu.', content: ['Ukhuwah adalah ikatan yang perlu dirawat melalui kebiasaan yang sederhana tetapi konsisten. Menjaga lisan, menghormati perbedaan, dan membantu sesama merupakan bagian dari adab bermasyarakat.', 'Lingkungan masjid dapat menjadi ruang yang mempertemukan jamaah dalam semangat ibadah sekaligus membangun kepedulian sosial.', 'Dengan menjaga adab dalam keseharian, hubungan antarjamaah dapat tumbuh lebih sehat dan saling menguatkan.'] },
  { slug: 'keutamaan-sedekah-dan-kepedulian-sosial', category: 'Kajian', title: 'Keutamaan Sedekah dan Kepedulian Sosial', date: '25 Agustus 2026', excerpt: 'Sedekah dapat menjadi kebiasaan yang memperkuat kepedulian dan kebermanfaatan sosial.', content: ['Sedekah tidak terbatas pada nominal, tetapi juga berkaitan dengan keikhlasan dan kemauan berbagi manfaat.', 'Program sosial masjid dapat menjadi wadah bagi jamaah untuk menyalurkan kepedulian secara terarah.', 'Kebiasaan berbagi yang dilakukan bersama dapat membentuk lingkungan yang lebih peka terhadap kebutuhan sesama.'] },
  { slug: 'membiasakan-interaksi-dengan-al-quran-di-rumah', category: 'Al-Qur’an', title: 'Membiasakan Interaksi dengan Al-Qur’an di Rumah', date: '21 Agustus 2026', excerpt: 'Kebiasaan kecil yang dilakukan rutin dapat membantu membangun kedekatan keluarga dengan Al-Qur’an.', content: ['Interaksi dengan Al-Qur’an dapat dimulai dengan waktu membaca yang realistis dan konsisten.', 'Orang tua memiliki peran penting dalam memberikan contoh dan menciptakan suasana belajar yang menyenangkan bagi anak.', 'Kebiasaan membaca, memahami, dan mengamalkan nilai Al-Qur’an dapat tumbuh melalui praktik sederhana setiap hari.'] },
  { slug: 'membangun-tradisi-saling-menolong-di-lingkungan-masjid', category: 'Akhlak', title: 'Membangun Tradisi Saling Menolong di Lingkungan Masjid', date: '18 Agustus 2026', excerpt: 'Masjid dapat menjadi pusat tumbuhnya budaya tolong-menolong dan kepedulian antarjamaah.', content: ['Tolong-menolong dapat diwujudkan dalam banyak bentuk, mulai dari membantu kegiatan masjid hingga memperhatikan kebutuhan tetangga.', 'Budaya tersebut membutuhkan koordinasi yang baik agar bantuan dapat diberikan secara tepat dan berkelanjutan.', 'Keterlibatan jamaah dari berbagai usia membuat pelayanan sosial masjid semakin kuat.'] },
  { slug: 'menata-niat-dan-waktu-untuk-ibadah', category: 'Fiqih', title: 'Menata Niat dan Waktu untuk Ibadah yang Lebih Baik', date: '14 Agustus 2026', excerpt: 'Pengelolaan waktu yang baik membantu menjaga konsistensi ibadah di tengah aktivitas harian.', content: ['Kesibukan perlu dikelola agar kewajiban dan amalan utama tetap mendapatkan ruang.', 'Membuat prioritas sederhana dapat membantu menjaga jadwal ibadah tanpa harus menunggu waktu yang benar-benar longgar.', 'Konsistensi lebih penting daripada target yang terlalu berat tetapi sulit dijaga.'] },
  { slug: 'mendidik-anak-mencintai-masjid-sejak-dini', category: 'Pendidikan', title: 'Mendidik Anak Mencintai Masjid Sejak Dini', date: '10 Agustus 2026', excerpt: 'Pengalaman positif di masjid dapat membantu anak membangun kedekatan dengan lingkungan ibadah.', content: ['Anak membutuhkan lingkungan yang aman dan menyenangkan ketika mulai mengenal masjid.', 'Kegiatan pendidikan, bermain yang terarah, dan keteladanan orang dewasa dapat membangun pengalaman positif.', 'Pelibatan anak secara bertahap membuat mereka merasa menjadi bagian dari komunitas masjid.'] },
]
