import SiteShell from '@/components/layout/SiteShell'
import PageIntro from '@/components/content/PageIntro'
import { FileDown } from 'lucide-react'

const openingBalance = 9_750_000
const transactions=[['01 Sep','Kotak amal Jumat','Pemasukan',2_500_000],['02 Sep','Donasi jamaah','Pemasukan',4_000_000],['03 Sep','Pembayaran listrik','Pengeluaran',1_200_000],['05 Sep','Operasional kajian','Pengeluaran',750_000],['08 Sep','Infak kegiatan sosial','Pemasukan',1_500_000],['10 Sep','Perawatan fasilitas','Pengeluaran',500_000]] as const
const income = transactions.filter(([, , type]) => type === 'Pemasukan').reduce((sum, [, , , amount]) => sum + amount, 0)
const expense = transactions.filter(([, , type]) => type === 'Pengeluaran').reduce((sum, [, , , amount]) => sum + amount, 0)
const closingBalance = openingBalance + income - expense
const rupiah = (value:number) => `Rp ${value.toLocaleString('id-ID')}`

export default function KeuanganPage(){return <SiteShell><main id="main-content" className="inner-page"><div className="container"><PageIntro eyebrow="Akuntabilitas Publik" title="Transparansi Keuangan" description="Ringkasan pemasukan dan pengeluaran Masjid Miftahul Mubin sebagai bentuk keterbukaan kepada jamaah dan masyarakat."/><section className="finance-disclosure"><span className="eyebrow">Data contoh Fase 1</span><strong>Angka pada halaman ini adalah simulasi</strong><p>Nilai akan digantikan oleh catatan bendahara setelah modul database dan audit diterapkan.</p></section><div className="finance-summary-page"><div><span>Saldo Awal</span><strong>{rupiah(openingBalance)}</strong></div><div><span>Total Pemasukan</span><strong>{rupiah(income)}</strong></div><div><span>Total Pengeluaran</span><strong>{rupiah(expense)}</strong></div><div><span>Saldo Akhir</span><strong>{rupiah(closingBalance)}</strong></div></div><div className="finance-period"><strong>September 2026</strong><span>Laporan berjalan</span><button type="button" className="report-button"><FileDown size={15}/> PDF</button></div><div className="finance-table-wrap"><table><thead><tr><th>Tanggal</th><th>Keterangan</th><th>Jenis</th><th>Nominal</th></tr></thead><tbody>{transactions.map(([date,desc,type,amount])=><tr key={desc}><td>{date}</td><td>{desc}</td><td><span className={type==='Pemasukan'?'finance-in':'finance-out'}>{type}</span></td><td className="amount">{type==='Pemasukan'?'+':'−'} {rupiah(amount)}</td></tr>)}</tbody></table></div><div className="finance-note"><span className="eyebrow">Prinsip pelaporan</span><p>Laporan publik akan memuat periode, saldo awal, transaksi masuk dan keluar, saldo akhir, kategori, dan pada tahap berikutnya tautan bukti transaksi sesuai kebijakan pengurus.</p></div></div></main></SiteShell>}
