'use client'

import { useEffect, useState } from 'react'
import { Edit3, FilePlus2, Loader2, Trash2, X } from 'lucide-react'
import { supabase } from '@/lib/supabase/client'

type Album = { id:string; title:string; slug:string; description:string|null; cover_url:string|null }
const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9\s-]/g,'').replace(/\s+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'')

export default function AdminDocumentationAlbums(){
 const [rows,setRows]=useState<Album[]>([]),[editing,setEditing]=useState<Album|null|false>(false),[form,setForm]=useState({title:'',slug:'',description:'',cover_url:''}),[error,setError]=useState(''),[saving,setSaving]=useState(false)
 async function load(){const r=await supabase.from('media_albums').select('id,title,slug,description,cover_url').order('created_at',{ascending:false});if(r.error)setError('Album gagal dimuat.');else setRows((r.data??[]) as Album[])}
 useEffect(()=>{void load()},[])
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);const payload={title:form.title.trim(),slug:slugify(form.slug||form.title),description:form.description.trim()||null,cover_url:form.cover_url.trim()||null};const r=editing?await supabase.from('media_albums').update(payload).eq('id',editing.id):await supabase.from('media_albums').insert(payload);if(r.error)setError(r.error.code==='23505'?'Slug album sudah digunakan.':'Album gagal disimpan.');else{setEditing(false);setForm({title:'',slug:'',description:'',cover_url:''});await load()}setSaving(false)}
 async function remove(id:string){if(!window.confirm('Hapus album ini? Media di dalamnya ikut terhapus.'))return;const r=await supabase.from('media_albums').delete().eq('id',id);if(r.error)setError('Album gagal dihapus.');else await load()}
 return <section className="admin-news-manager"><div className="admin-module-toolbar"><strong>Album Dokumentasi</strong><button className="admin-button primary" onClick={()=>{setForm({title:'',slug:'',description:'',cover_url:''});setEditing(null)}}><FilePlus2 size={17}/> Tambah album</button></div>{error&&<p className="admin-form-error">{error}</p>}<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Album</th><th>Slug</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.title}</strong></td><td>/{r.slug}</td><td><button className="admin-icon-button" onClick={()=>{setForm({title:r.title,slug:r.slug,description:r.description||'',cover_url:r.cover_url||''});setEditing(r)}}><Edit3 size={16}/></button><button className="admin-icon-button danger" onClick={()=>void remove(r.id)}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>{editing!==false&&<div className="admin-modal-backdrop"><div className="admin-modal"><div className="admin-modal-header"><h2>{editing?'Edit':'Tambah'} album</h2><button className="admin-icon-button" onClick={()=>setEditing(false)}><X size={18}/></button></div><form className="admin-editor-form" onSubmit={save}><label><span>Nama album</span><input required value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value,slug:v.slug||slugify(e.target.value)}))}/></label><label><span>Slug</span><input required value={form.slug} onChange={e=>setForm(v=>({...v,slug:slugify(e.target.value)}))}/></label><label><span>Deskripsi</span><textarea rows={3} value={form.description} onChange={e=>setForm(v=>({...v,description:e.target.value}))}/></label><label><span>URL cover</span><input type="url" value={form.cover_url} onChange={e=>setForm(v=>({...v,cover_url:e.target.value}))}/></label><div className="admin-modal-actions"><button type="button" className="admin-button secondary" onClick={()=>setEditing(false)}>Batal</button><button className="admin-button primary" disabled={saving}>{saving?<><Loader2 className="spin" size={16}/> Menyimpan…</>:'Simpan'}</button></div></form></div></div>}</section>
}
